import streamlit as st

from pages.command_center.services.command_center_service import (
    CommandCenterService
)

from components.widgets.section_header import (
    SectionHeader
)

from components.widgets.executive_banner import (
    ExecutiveBanner
)

from components.widgets.executive_kpi_strip import (
    ExecutiveKPIStrip
)

from components.executive.executive_brief import (
    ExecutiveBrief
)

from components.widgets.domain_health_matrix import (
    DomainHealthMatrix
)

from components.widgets.event_feed import (
    EventFeed
)

from components.widgets.critical_signal_panel import (
    CriticalSignalPanel
)

from components.widgets.forecast_summary import (
    ForecastSummary
)

from components.widgets.action_summary import (
    ActionSummary
)

from components.graphs.dependency_graph import (
    DependencyGraph
)

from components.graphs.impact_graph import (
    ImpactGraph
)


class CommandCenterPage:

    def __init__(self):

        self.service = (
            CommandCenterService()
        )

        self.section_header = (
            SectionHeader()
        )

        self.banner = (
            ExecutiveBanner()
        )

        self.kpi_strip = (
            ExecutiveKPIStrip()
        )

        self.executive_brief = (
            ExecutiveBrief()
        )

        self.domain_matrix = (
            DomainHealthMatrix()
        )

        self.events = (
            EventFeed()
        )

        self.signal_panel = (
            CriticalSignalPanel()
        )

        self.forecast_summary = (
            ForecastSummary()
        )

        self.action_summary = (
            ActionSummary()
        )

    def render(self):

        data = (
            self.service.get_data()
        )

        state = data.get(
            "state",
            {}
        )

        summary = data.get(
            "summary",
            {}
        )

        signals = data.get(
            "signals",
            []
        )

        impacts = data.get(
            "impacts",
            []
        )

        forecasts = data.get(
            "forecasts",
            {}
        )

        memory = data.get(
            "memory",
            []
        )

        autonomy = data.get(
            "autonomy",
            {}
        )

        domain_health = data.get(
            "domain_health",
            {}
        )

        self.banner.render(

            title=
            "ICTA Executive Command Center",

            subtitle=
            "Real-Time Yatra Operations Intelligence"
        )

        st.markdown("---")

        self.section_header.render(

            "Executive Overview",

            "Real-time summary of operational risk, signals, forecasts and actions."
        )

        self.kpi_strip.render(
            summary
        )

        st.markdown("---")

        self.section_header.render(

            "Executive AI Brief",

            "AI-generated summary of current operational conditions."
        )

        self.executive_brief.render(

            summary,

            signals
        )

        st.markdown("---")

        col1, col2 = st.columns(
            [2, 1]
        )

        with col1:

            self.section_header.render(

                "Critical Signals",

                "High-priority operational events requiring attention."
            )

            self.signal_panel.render(
                signals
            )

        with col2:

            self.section_header.render(

                "Domain Health",

                "Current status across monitored operational domains."
            )

            self.domain_matrix.render(
                domain_health
            )

        st.markdown("---")

        col1, col2 = st.columns(2)

        with col1:

            self.section_header.render(

                "Forecast Intelligence",

                "Predicted operational conditions and emerging risks."
            )

            self.forecast_summary.render(
                forecasts
            )

        with col2:

            self.section_header.render(

                "Recommended Actions",

                "Suggested and autonomous actions generated by the platform."
            )

            self.action_summary.render(

                autonomy.get(
                    "execution_logs",
                    []
                )
            )

        st.markdown("---")

        self.section_header.render(

            "Dependency Intelligence",

            "Cross-domain relationships and cascading operational impacts."
        )

        DependencyGraph(

            relationships=
            state.get(
                "dependencies",
                []
            )

        ).render()

        st.markdown("---")

        self.section_header.render(

            "Impact Projection",

            "Expected downstream effects of current operational conditions."
        )

        ImpactGraph().render(
            impacts
        )

        st.markdown("---")

        self.section_header.render(

            "Operational Timeline",

            "Chronological view of key events, signals and actions."
        )

        self.events.render(
            memory
        )